version: '3'

services:
  mariadb:
    image: mariadb:latest
    restart: always
    ports:
      - "3310:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8089:80"
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_HOST=mariadb

volumes:
  mariadb_data:
